### ISSUE TITLE
:cricket: Extract meta data from uploaded image

### ISSUE THREAD

**Issue by Primajin** [opendata-apps/mantis#9]
Hey there, I just found this incredible project and added my sightings. Thanks a lot for this, really cool project!

Do you think it is possible to read the meta-data from the uploaded image and already pre-fill the fields that you can extract from there - e.g. longitude, latitude, time of day, ... so that the user doesn't have to add it by hand?

Thanks a lot in advance for considering it 👍🏻

**Comment by LeonKohli** [comment]
Thanks @Primajin  for your feedback and sightings!

We already use exif-js to pre-fill longitude and latitude from image metadata. Your suggestion to include time/date is great - we'll consider it for future updates.

The feature works well on most platforms, but there's an Android-specific issue:

On Android, due to a [known limitation](https://stackoverflow.com/questions/70865878/picking-photo-from-web-in-android-no-longer-includes-exif-gps-location), the Media Picker doesn't include EXIF data correctly.

Android users can work around this:
1. Click the three-dot menu (⋮)
2. Choose "Browse..."
3. Select the image from the Files app

This method preserves metadata, allowing to pre-fill the fields.

Thanks for your input! We're always looking to improve, so keep the ideas coming. 🦗

**Comment by Primajin** [comment]
Ahh ok - it didn't work for me. I have used the upload in the browser (Chrome 128.0.6613.84) but it didn't prefil my GPS data from the image:

![Screenshot 2024-08-26 090517](https://github.com/user-attachments/assets/2eb8d7ff-07f4-4796-8d78-c891d186c0f2)

Here is the image as zip (so that Github doesn't tinker with the exif) in case you want to test it.
[PXL_20240824_193258837.MP.zip](https://github.com/user-attachments/files/16745303/PXL_20240824_193258837.MP.zip)

Thanks again and all the best
Jannis

**Comment by LeonKohli** [comment]
Hey @Primajin 
Thanks for the test image and follow-up.
We've fixed the issue in our latest commit. It now works with all our test images containing coordinates including yours.
The update will be deployed soon. 🦗

**Comment by Primajin** [comment]
Awesome!
